############# English navigation ##############

# main menu
[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "Community"
pageRef = "/about"
weight = 2

[[main]]
name = "Podcast"
pageRef = "/elements"
weight = 3

[[main]]
weight = 4
name = "Pages"

[[main]]
parent = "Pages"
name = "Jobs"
pageRef = "/blog"

[[main]]
parent = "Pages"
name = "Team"
pageRef = "/authors"

[[main]]
parent = "Pages"
name = "Webiners"
pageRef = "/categories"


# footer menu
[[footer]]
name = "About"
pageRef = "/about"
weight = 1

[[footer]]
name = "Podcast"
pageRef = "/elements"
weight = 2

[[footer]]
name = "Privacy Policy"
pageRef = "/privacy-policy"
weight = 3
