version: 2
updates:
- package-ecosystem: npm
  directory: "/exampleSite/"
  schedule:
    interval: daily
    time: "20:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  labels:
  - automerge
