name = "Blonde"
license = "MIT"
licenselink = "https://github.com/opera7133/Blonde/blob/master/LICENSE"
description = "Blonde, A simple theme using Tailwind CSS"

homepage = "https://github.com/opera7133/Blonde"

demosite = "https://blonde.pages.dev"

tags = ["blog", "minimal", "light", "dark", "simple", "clean", "tailwindcss", "personal", "responsive"]
features = ["blog"]

[author]
  name = "wamo"
  homepage = "https://wmsci.com"
